id: P56B643F5
initial_creation_type: ocr
source_metadata:
  volumes:
    0d5dfb7f29fe4d85a801c58c4e666177:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: དཔལ་བཅོམ་ལྡན་འདས་ཀྱི་མངོན་པར་རྟོགས་པ།
      total_pages: 2107
      volume_number: 11
